name: make and build

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: bash make.sh

      - run: npm install

      - run: node book-build.js

      - uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: "CI: make and build"
          branch: ${{ github.head_ref }}
